URL_HOME = 'https://stellarburgers.nomoreparties.site/'
URL_LOGIN = 'https://stellarburgers.nomoreparties.site/login'
URL_PASS_REC = 'https://stellarburgers.nomoreparties.site/forgot-password'
URL_PROFILE = 'https://stellarburgers.nomoreparties.site/account/profile'
URL_ORDER_HISTORY = 'https://stellarburgers.nomoreparties.site/account/order-history'

USERNAME = f'eldar_dikopp_10_012'
LOG_EMAIL = f'{USERNAME}@yandex.ru'
PAS = f'123456789'
REG_PASSWORD = f'123321'
REG_PASSWORD_ERROR = f'123'
