from selenium.webdriver.common.by import By


class Locators:
    BUTTON_PASS_LINK = (By.XPATH, ".//div/p/a[@href= '/forgot-password']")
    TAG_PASS_REC = (By.XPATH, ".//button[text() = 'Восстановить']")
    CONT_PASS_REC_EMAIL = (By.XPATH, ".//div[@class = 'input__container']//input")
    BUTTON_PASS_REC = (By.XPATH, ".//button[text() = 'Восстановить']")
    BUTTON_PASS_SAVE = (By.XPATH, ".//div/label[text() = 'Введите код из письма']")
    BUTTON_PASS_VIS = (By.XPATH, ".//div[@class = 'input__icon input__icon-action']")
    CONT_PASS_ACTIVE = (By.XPATH, ".//div/div[contains(@class, 'input_status_active')]")
    CONT_LOGIN_EMAIL = (By.XPATH, ".//div/label[text()='Email']/../input")
    CONT_LOGIN_PASS = (By.XPATH, ".//div/label[text()='Пароль']/../input")
    BUTTON_LOGIN = (By.XPATH, ".//button[text() = 'Войти']")
    BUTTON_ACCOUNT = (By.XPATH, ".//p[text() = 'Личный Кабинет']")
    BUTTON_ORDER_HISTORY = (By.XPATH, ".//ul/li/a[text() = 'История заказов']")
    BUTTON_QUIT_PROFILE = (By.XPATH, ".//ul/li/button[text() = 'Выход']")
    LIST_ORDER_HISTORY = (By.XPATH, ".//div/ul[contains(@class, 'OrderHistory')]")
    BUTTON_PLACE_ORDER = (By.XPATH, ".//button[text() = 'Оформить заказ']")
    TAG_LOGIN = (By.XPATH, ".//div[contains(@class, 'Auth_login')]/h2[text() = 'Вход']")
    TAG_RECOVERY = (By.XPATH, ".//div[contains(@class, 'Auth_login')]/h2[text() = 'Восстановление пароля']")
    BUTTON_CONSTRUCTOR = (By.XPATH, ".//p[text() = 'Конструктор']")
    TAG_CONSTRUCTOR = (By.XPATH, ".//section[contains(@class, 'BurgerIngredients')]/h1[text() = 'Соберите бургер']")
    LIST_CONSTRUCTOR = (By.XPATH, ".//div[contains(@class, 'BurgerIngredients')]")
    BUTTON_ORDER_LIST = (By.XPATH, ".//nav/ul/li[contains(@class, 'undefined')]/a")
    TAG_ORDER_LIST = (By.XPATH, ".//h1[text() = 'Лента заказов']")
    LIST_ORDER_LIST = (By.XPATH, ".//div[contains(@class, 'OrderFeed']/ul[contains(@class, 'OrderFeed']")
    BUTTON_INGREDIENT = (By.XPATH, ".//div[contains(@class, 'BurgerIngredients')]/ul/a")
    WINDOW_INGREDIENT = (By.XPATH, ".//section[contains(@class, 'modal_opened')]/div[contains(@class, 'modal__container')]")
    TAG_WINDOW_INGREDIENT = (By.XPATH, ".//h2[text() = 'Детали ингредиента']")
    BUTTON_QUIT_ING_WINDOW = (By.XPATH, ".//button[contains(@class, 'close_modified')]")
    CONT_BURGER_BASKET = (By.XPATH, ".//div[@class = 'constructor-element constructor-element_pos_top']")
    TAG_INGREDIENT_COUNTER = (By.XPATH, ".//div[contains(@class, 'BurgerIngredients')]/ul/a/div/p")
    BUTTON_ORDER = (By.XPATH, ".//button[text() = 'Оформить заказ']")
    TAG_ORDER_SUCCESS = (By.XPATH, ".//div[contains(@class, 'contentBox')]//p[text() = 'идентификатор заказа']")
